/*
 * Kibl Sports API - Outbound
 *
 * Kibl Sports API - Outbound
 *
 * API version: 1.0.0
 * Contact: developers@jindogroup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type CombinedLineType struct {
	CombinedLineTypeId int64 `json:"combined_line_type_id"`
	MarketTypeId1      int64 `json:"market_type_id_1"`
	MarketTypeId2      int64 `json:"market_type_id_2"`
}
