/*
 * Kibl Sports API - Outbound
 *
 * Kibl Sports API - Outbound
 *
 * API version: 1.0.0
 * Contact: developers@jindogroup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

import "github.com/antihax/optional"

type Fixture struct {
	FixtureId           int64                  `json:"fixture_id"`
	LeagueId            int64                  `json:"league_id"`
	SeasonId            int64                  `json:"season_id"`
	LocationId          int64                  `json:"location_id"`
	FixtureTypeId       int64                  `json:"fixture_type_id"`
	StartTime           string                 `json:"start_time"`
	CutoffTime          string                 `json:"cutoff_time"`
	Name                string                 `json:"name"`
	InsertedOn          string                 `json:"inserted_on"`
	Participants        []FixturesParticipants `json:"participants"`
	Information         []FixtureInformation   `json:"informations,omitempty"`
	States              []interface{}          `json:"states,omitempty"`
	FixtureExternalRefs []FixtureExternalRef   `json:"fixture_reference_external_ids,omitempty"`
}

type FixturesParticipants struct {
	FixtureParticipantId int64  `json:"fixture_participant_id"`
	FixtureId            int64  `json:"fixture_id"`
	ParticipantId        int64  `json:"participant_id"`
	SideId               int64  `json:"side_id"`
	Ordering             int64  `json:"ordering"`
	Rotation             int64  `json:"rotation"`
	InsertedOn           string `json:"inserted_on"`
}

type FixtureExternalRef struct {
	FixtureId    int64  `json:"fixture_id"`
	FeedSourceId int64  `json:"feed_source_id"`
	FeedId       int64  `json:"feed_id"`
	FeedName     string `json:"feed_name"`
}

type FixtureInformation struct {
	FixtureInformationId int64  `json:"fixture_information_id"`
	FixtureId            int64  `json:"fixture_id"`
	InformationId        int64  `json:"information_id"`
	Value                string `json:"value"`
	InsertedOn           string `json:"inserted_on"`
}

type OptionalFixtureInfoParams struct {
	FixtureId optional.Int64
}

type FixturesByRotation struct {
	Fixture
}

type FixturesByTeam struct {
	Fixture
}

type FixtureMapping struct {
	FeedFixtureMappingId int64  `json:"feed_fixture_mapping_id"`
	FixtureId            int64  `json:"fixture_id"`
	FeedSourceId         int64  `json:"feed_source_id"`
	FeedId               int64  `json:"feed_id"`
	FeedName             string `json:"feed_name"`
	InsertedOn           string `json:"inserted_on"`
}

type OptionalFixtureMappingParams struct {
	LeagueId  optional.Int64
	FixtureId optional.Int64
	StartTime optional.Time
}

type OptionalFixturesInfoParams struct {
	FixtureId          optional.Int64
	StartTime          optional.Time
	IncludeExternalIds []string
	ExternalLeagueId   *LeagueMappingParam
}

type OptionalFixturesInfoByRotationParams struct {
	IncludeExternalIds []string
}

type OptionalFixturesInfoByTeamsParams struct {
	IncludeExternalIds []string
}

type FixtureType struct {
	FixtureTypeId int64  `json:"fixture_type_id"`
	Name          string `json:"name"`
	Abrv          string `json:"abrv"`
	InsertedOn    string `json:"inserted_on"`
}

type FixtureTypeMapping struct {
	FeedFixtureTypeMappingId int64  `json:"feed_fixture_type_mapping_id"`
	FixtureTypeId            int64  `json:"fixture_type_id"`
	FeedSourceId             int64  `json:"feed_source_id"`
	FeedId                   int64  `json:"feed_id"`
	FeedName                 string `json:"feed_name"`
	FeedAbrv                 string `json:"feed_abrv"`
	InsertedOn               string `json:"inserted_on"`
}
