/*
 * Kibl Sports API - Outbound
 *
 * Kibl Sports API - Outbound
 *
 * API version: 1.0.0
 * Contact: developers@jindogroup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

import "github.com/antihax/optional"

type Outcome struct {
	OutcomeId  int64  `json:"outcome_id"`
	FixtureId  int64  `json:"fixture_id"`
	SegmentId  int64  `json:"segment_id"`
	Clock      string `json:"clock"`
	IsFinal    bool   `json:"is_final"`
	InsertedOn string `json:"inserted_on"`
}

type OptionalOutcomeParticipantInfoParams struct {
	OutcomeId optional.Int64
}

type OptionalOutcomeInfoParams struct {
	FixtureId optional.Int64
}

type OutcomeParticipant struct {
	OutcomeParticipantId int64  `json:"outcome_participant_id"`
	OutcomeId            int64  `json:"outcome_id"`
	FixtureParticipantId int64  `json:"fixture_participant_id"`
	Score                string `json:"score"`
	IsWinner             bool   `json:"is_winner"`
	InsertedOn           string `json:"inserted_on"`
}
