/*
 * Kibl Sports API - Outbound
 *
 * Kibl Sports API - Outbound
 *
 * API version: 1.0.0
 * Contact: developers@jindogroup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

import "github.com/antihax/optional"

type PlayerNews struct {
	ParticipantId           int64                     `json:"participant_id"`
	Name                    string                    `json:"name"`
	PlayerNewsId            int64                     `json:"player_news_id"`
	PlayerId                int64                     `json:"player_id"`
	InjuryLocationId        int64                     `json:"injury_location_id"`
	FixtureId               int64                     `json:"fixture_id"`
	Status                  string                    `json:"status"`
	IsImportant             bool                      `json:"is_important"`
	IsHighlighted           bool                      `json:"is_highlighted"`
	IsHealed                bool                      `json:"is_healed"`
	InsertedOn              string                    `json:"inserted_on"`
	Comment                 string                    `json:"comment"`
	Impact                  string                    `json:"impact"`
	Headline                string                    `json:"headline"`
	LineId                  int64                     `json:"line_id"`
	MoreName                string                    `json:"more_name"`
	MoreLink                string                    `json:"more_link"`
	LastUpdated             string                    `json:"last_updated"`
	Participants            []PlayerInjuryParticipant `json:"participant"`
	ParticipantExternalRefs []ParticipantExternalRef  `json:"participant_reference_external_ids,omitempty"`
}

type OptionalPlayerNewsInfoParams struct {
	ParticipantId         optional.Int64
	PlayerId              optional.Int64
	PlayerNewsId          optional.Int64
	SinceLastUpdated      optional.Time
	IncludeExternalIds    []string
	ExternalParticipantId *ParticipantMappingParam
}
